services:
  - type: cron
    name: benfica-ticket-checker
    schedule: "@hourly"  # corre de hora a hora (podes ajustar)
    runtime: python
    plan: free
    buildCommand: "playwright install chromium"
    startCommand: "python check_benfica_tickets.py"

  - type: cron
    name: odisseias-ticket-checker
    schedule: "@hourly"
    runtime: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install playwright
      playwright install chromium
    startCommand: python odisseias/odisseias_checker.py
    envVars:
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false



  - type: web
    name: controlo-bilhetes-api
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      python -m playwright install chromium --target=/opt/render/project/.playwright
    startCommand: bash start.sh
    envVars:
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_FROM
        sync: false
      - key: EMAIL_TO
        sync: false
      - key: PLAYWRIGHT_BROWSERS_PATH
        value: /opt/render/project/.playwright

