name: Executar Email Reader

on:
  schedule:
    - cron: '0 9 * * *'  # corre todos os dias às 9h UTC (10h em Portugal)
  workflow_dispatch:     # permite correr manualmente


jobs:
  executar-script:
    runs-on: ubuntu-latest

    env:
      EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
      EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Executar script de email
        run: python src/email_reader.py

